### ISSUE TITLE
Unable to load without vosk

### ISSUE THREAD

**Issue by Baspla** [ElishaAz/mau_local_stt#1]
I can't start the instance without vosk.
Since there is no alpine/musl version of vosk i tried to run it without but it fails when loading.

Here is the error from maubot: [stacktrace.txt](https://github.com/ElishaAz/mau_local_stt/files/12100919/stacktrace.txt)

And my Maubot image with the dependencies: [Dockerfile.txt](https://github.com/ElishaAz/mau_local_stt/files/12100920/Dockerfile.txt)

**Comment by ElishaAz** [comment]
Thanks for the report. It should be fixed now.

**Comment by Baspla** [comment]
Incredible response time 😅. Love the project. 👍
